#!/bin/bash

docker stop docker-watchtower-1

cd allora-huggingface-walkthrough
sed -i 's/^\s*-\s*"8000:\(8000\)"/      - "8044:\1"/g' allora-huggingface-walkthrough/docker-compose.yaml
docker compose down
sudo sed -i 's/8000/8044/g' ~/allora-huggingface-walkthrough/config.json
./init.config
docker compose up --build -d
docker logs -fn100 worker
