#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

# Menu
PS3='Select an action: '
options=(
"Install Node"
"Update"
"Delete"
"Exit")

select opt in "${options[@]}"
do
case $opt in
"Install Node")

#===============================================================

# Update the repositories
sudo apt update
sudo apt install make clang pkg-config libssl-dev build-essential -y
if command -v rustup &> /dev/null; then
    rustup update
else
    curl https://sh.rustup.rs -sSf | sh
    source $HOME/.cargo/env
    rustup update nightly
    rustup target add wasm32-unknown-unknown --toolchain nightly ;
fi
rustc --version

#-----------------------------------------------------

cd $HOME
git clone https://github.com/availproject/avail-light.git
cd avail-light
git checkout v1.7.4
cargo build --release
cp target/release/avail-light /usr/local/bin/avail_light
avail_light --version

#-----------------------------------------------------

sudo bash -c "cat > $HOME/avail-light/config.yaml" <<EOF
log_level = "info"
http_server_host = "127.0.0.1"
http_server_port = 7000

libp2p_port = "37000"

full_node_rpc = ["http://127.0.0.1:9946"]
full_node_ws = ["ws://127.0.0.1:9946"]
app_id = 0
confidence = 92.0
avail_path = "$HOME/.avail-light"
prometheus_port = 9520
# Set to actual bootstrap peer ID and multiaddress
bootstraps = [["12D3KooWStAKPADXqJ7cngPYXd2mSANpdgh1xQ34aouufHA2xShz", "/ip4/127.0.0.1/tcp/39000"]]
EOF

#-----------------------------------------------------

sudo bash -c "cat > /etc/systemd/system/avail_light.service" <<EOF
[Unit] 
Description=Avail Light Client
After=network.target
StartLimitIntervalSec=0
[Service] 
User=$USER 
ExecStart=$(which avail_light) --network goldberg --config $HOME/avail-light/config.yaml
Restart=always 
RestartSec=120
[Install] 
WantedBy=multi-user.target
EOF

#-----------------------------------------------------

systemctl daemon-reload
systemctl enable avail_light
systemctl restart avail_light

#-----------------------------------------------------

echo '=============== INSLALL FINISHED ==================='
echo -e "To check logs:           \e[1m\e[33msudo journalctl -u avail_light -f -o cat\e[0m"

break
;;

#===========================================================================

"Update")

sudo systemctl stop avail_light
cd ~/avail-light && git fetch
git checkout v1.7.4
cargo build --release
cp target/release/avail-light /usr/local/bin/avail_light
avail_light --version
sudo systemctl restart avail_light

echo '=============== UPDATE FINISHED ==================='
echo -e "To check logs:           \e[1m\e[33msudo journalctl -u avail_light -f -o cat\e[0m"

break
;;

#===========================================================================

"Exit")
exit
;;
*) echo "Invalid option. Please try again.";;
esac

done
