#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

if [ -z "$MONIKER" ]; then
  echo "*********************"
  echo -e "\e[1m\e[34m		Lets's begin\e[0m"
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your MONIKER:\e[0m"
  echo "*********************"
  read MONIKER
  echo 'export MONIKER='$MONIKER >> $HOME/.bash_profile
  source ~/.bash_profile
fi

# Menu
PS3='Select an action: '
options=(
"Install Node"
"Update"
"Delete"
"Exit")

select opt in "${options[@]}"
do
case $opt in
"Install Node")

#===============================================================

# Update the repositories
sudo apt update
sudo apt install make clang pkg-config libssl-dev build-essential protobuf-compiler -y
if [ "$(rustc --version)" != "rustc 1.73.0 (cc66ad468 2023-10-03)" ]; then
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly ;
fi
rustc --version

ufw allow 45333
ufw allow 9945

cd $HOME
git clone https://github.com/availproject/avail
cd avail/
git checkout v1.8.0.4
cargo build --release -p data-avail
cp target/release/data-avail /usr/local/bin/avail
avail --version

sudo bash -c "cat > /etc/systemd/system/availd.service" <<EOF
[Unit]
Description=Avail Validator
After=network.target
StartLimitIntervalSec=0

[Service]
User=$USER
Type=simple
Restart=always
RestartSec=120
ExecStart=$(which avail) \
  --base-path $HOME/.avail/data/ \
  --node-key-file "$HOME/.avail/node-key" \
  --port 45333 \
  --rpc-port 9946 \
  --chain goldberg \
  --validator \
  --name $MONIKER \
  --telemetry-url 'ws://telemetry.avail.tools:8001/submit/ 0'

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable availd
systemctl restart availd

echo '=============== INSLALL FINISHED ==================='
echo -e "To check logs:                \e[1m\e[33msudo journalctl -u availd -f -o cat\e[0m"
echo -e "To check node in telemetry:   \e[1m\e[33mhttps://telemetry.avail.tools/#list/0x6f09966420b2608d1947ccfb0f2a362450d1fc7fd902c29b67c906eaa965a7ae\e[0m"

break
;;

#===========================================================================

"Update")

systemctl stop availd
cd ~/avail && git fetch
git checkout v1.8.0.4
cargo build --release -p data-avail
cp target/release/data-avail /usr/local/bin/avail
avail --version
systemctl restart availd

echo '=============== UPDATE FINISHED ==================='
echo -e "To check logs:                \e[1m\e[33msudo journalctl -u availd -f -o cat\e[0m"

break
;;

#===========================================================================

"Exit")
exit
;;
*) echo "Invalid option. Please try again.";;
esac

done
