#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

PS3='Select an action: '
options=(
"Install Node"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in
#================================================================

"Install Node")

if [ -z "$MONIKER" ]; then
  echo "*********************"
  echo -e "\e[1m\e[34m		Lets's begin\e[0m"
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your MONIKER:\e[0m"
  echo "*********************"
  read MONIKER
  echo 'export MONIKER='$MONIKER >> $HOME/.bash_profile
  source ~/.bash_profile
fi

if [ -z "$EVM_ADDRESS" ]; then
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your EVM_ADDRESS:\e[0m"
  echo "*********************"
  read EVM_ADDRESS
  echo 'export EVM_ADDRESS='$EVM_ADDRESS >> $HOME/.bash_profile
  source ~/.bash_profile
fi

echo -e "\e[1m\e[32m	Enter your Validator Privat key (only new wallet):\e[0m"
echo "*********************"
read SIGNER_PRIVATE_KEY

# Install Docker
if ! [ -x "$(command -v docker)" ]; then
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
sudo usermod -aG docker $USER
docker --version
else
echo $(docker --version)
fi

# Install Docker Compose
if ! [ -x "$(command -v docker-compose)" ]; then
sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
sudo chmod +x /usr/local/bin/docker-compose 
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version
else
echo $(docker-compose --version)
fi

mkdir elixir && cd elixir
sudo tee validator.env > /dev/null <<EOF
ENV=testnet-3
STRATEGY_EXECUTOR_IP_ADDRESS=$(curl -s https://checkip.amazonaws.com)
STRATEGY_EXECUTOR_DISPLAY_NAME=$MONIKER
STRATEGY_EXECUTOR_BENEFICIARY=$EVM_ADDRESS
SIGNER_PRIVATE_KEY=$SIGNER_PRIVATE_KEY
EOF

docker pull elixirprotocol/validator:v3

docker run -d \
  --env-file validator.env \
  --name elixir \
  --restart unless-stopped \
  -p 17690:17690 \
  elixirprotocol/validator:v3

cd $HOME

echo '=============== INSLALL FINISHED ==================='
echo -e "To check logs:    \e[1m\e[33mdocker logs -fn100 elixir\e[0m"

break
;;

#================================================================

"Delete Node")

break
;;

#================================================================

"Exit")
exit
esac
done
