#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

# Menu
PS3='Select an action: '
options=(
"Install Node"
"Delete"
"Exit")

select opt in "${options[@]}"
do
case $opt in
"Install Node")

#===========================================================================


if [ -z "$MONIKER" ]; then
  echo -e "      \e[1m\e[35m SET YOUR IDENTITY(nickname):\e[0m"
  echo "_|-_|-_|-_|-_|-_|-_|"
  read MONIKER
  echo "_|-_|-_|-_|-_|-_|-_|"
  echo "export MONIKER="${MONIKER}"" >> $HOME/.bash_profile
  source $HOME/.bash_profile
fi

## Installation

# 1. Update, upgrade and install requirements:
sudo apt-get update && \
sudo apt-get upgrade -y && \
sudo curl https://sh.rustup.rs -sSf | sh -s -- -y && \
source "$HOME/.cargo/env" && \
cargo install sccache && \
sudo apt-get install build-essential cmake clang pkg-config libssl-dev protobuf-compiler -y

# 2. Clone repository and build:
cd $HOME && git clone https://github.com/fleek-network/ursa && \
cd ursa && \
make install

# 3. Create a service:
sudo tee /etc/systemd/system/fleekd.service > /dev/null <<EOF
[Unit]
Description=Fleek Node
After=network.target
[Service]
User=$USER
Type=simple
ExecStart=$(which ursa)
Restart=on-failure
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

# 4. Restart the service:
sudo systemctl daemon-reload && \
sudo systemctl enable fleekd && \
sudo systemctl restart fleekd && \
sudo journalctl -u fleekd -f -o cat

# 5. Replace default identity:
systemctl stop fleekd && \
sed -i.bak -e "s/^identity *=.*/identity = \"${MONIKER}\"/" $HOME/.ursa/config.toml && \
rm $HOME/.ursa/keystore/*; \
sudo systemctl restart fleekd && \
sudo journalctl -u fleekd -f -o cat

# 6. Backup:
echo -e "      \e[1m\e[31m Please SAVE your keystore!!!  \e[0m"
echo -e "$HOME/.ursa/keystore/"

break
;;

#===========================================================================

"Delete")

sudo systemctl stop fleekd && \
sudo systemctl disable fleekd && \
rm /etc/systemd/system/fleekd.service && \
sudo systemctl daemon-reload && \
cd $HOME && \
rm -rf ursa .ursa && \
rm $(which fleekd)

break
;;

#===========================================================================

"Exit")
exit
;;
*) echo "Invalid option. Please try again.";;
esac

done
