#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

PS3='Select an action: '
options=(
"Install Node"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in
#================================================================

"Install Node")

sudo apt update

# Install Go
source <(curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/system/go)

git clone https://github.com/hemilabs/heminetwork.git
cd heminetwork
make deps
make install
cp ~/heminetwork/bin/popmd /usr/local/bin/ && cd

cd ~/heminetwork/bin && ./keygen -secp256k1 -json -net="testnet" > ~/heminetwork/bin/popm-address.json

sudo tee /root/heminetwork/.env > /dev/null <<EOF
POPM_BTC_PRIVKEY=$(jq -r '.private_key' ~/heminetwork/bin/popm-address.json)
POPM_STATIC_FEE=20
POPM_BFG_URL=wss://testnet.rpc.hemi.network/v1/ws/public
EOF

sudo tee /etc/systemd/system/popmd.service > /dev/null <<EOF
[Unit]
Description=Hemi Service
After=network.target

[Service]
User=root
Type=simple
EnvironmentFile=/root/heminetwork/.env
ExecStart=/usr/local/bin/popmd
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# Start the node
systemctl daemon-reload
systemctl enable popmd
systemctl restart popmd

echo '=============== INSLALL FINISHED ==================='
echo -e "To check logs:    \e[1m\e[33mjournalctl -u popmd -f -o cat\e[0m"

break
;;

#================================================================

"Delete Node")

break
;;

#================================================================

"Exit")
exit
esac
done
