#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

PS3='Select an action: '
options=(
"Install Node"
"Update Node"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in
#================================================================

"Install Node")

sudo apt update

# Install Go
source <(curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/system/go)

git clone https://github.com/hemilabs/heminetwork.git
cd heminetwork
make deps
make install
cp ~/heminetwork/bin/popmd /usr/local/bin/

cd ~/heminetwork/bin && ./keygen -secp256k1 -json -net="testnet" > ~/heminetwork/bin/popm-address.json && cd

sudo tee /root/heminetwork/.env > /dev/null <<EOF
POPM_BTC_PRIVKEY=$(jq -r '.private_key' ~/heminetwork/bin/popm-address.json)
POPM_STATIC_FEE=20
POPM_BFG_URL=wss://testnet.rpc.hemi.network/v1/ws/public
EOF

sudo tee /etc/systemd/system/popmd.service > /dev/null <<EOF
[Unit]
Description=Hemi Service
After=network.target

[Service]
User=root
Type=simple
EnvironmentFile=/root/heminetwork/.env
ExecStart=/usr/local/bin/popmd
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# Start the node
systemctl daemon-reload
systemctl enable popmd
systemctl restart popmd

echo '=============== INSLALL FINISHED ==================='
echo -e "To check logs:    \e[1m\e[33mjournalctl -u popmd -f -o cat\e[0m"

break
;;

#================================================================

"Update Node")

systemctl stop popmd
cd heminetwork
curl -L -O https://github.com/hemilabs/heminetwork/releases/download/v0.5.0/heminetwork_v0.5.0_linux_amd64.tar.gz
mkdir -p hemi
tar --strip-components=1 -xzvf heminetwork_v0.5.0_linux_amd64.tar.gz -C hemi
rm /usr/local/bin/popmd

sed -i 's/^POPM_STATIC_FEE=.*/POPM_STATIC_FEE=200/' /root/heminetwork/.env

sudo tee /etc/systemd/system/popmd.service > /dev/null <<EOF
[Unit]
Description=Hemi Service
After=network.target

[Service]
User=root
Type=simple
EnvironmentFile=/root/heminetwork/.env
ExecStart=/root/heminetwork/hemi/popmd
WorkingDirectory=/root/heminetwork/hemi/
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable popmd
systemctl restart popmd

echo '=============== UPDATE FINISHED ==================='
echo -e "To check logs:    \e[1m\e[33mjournalctl -u popmd -f -o cat\e[0m"

break
;;

#================================================================

"Delete Node")

break
;;

#================================================================

"Exit")
exit
esac
done
