#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

#=======================================================

# Menu
PS3='Select an action: '
options=(
"Install Node"
"Diskord Bot Autoinstall"
"Update"
"Delete"
"Exit")

#=======================================================

select opt in "${options[@]}"
do
case $opt in
"Install Node")

#----------------------------------------------------

if [ -z "$MONIKER" ]; then
  echo -e "      \e[1m\e[35m SET YOUR IDENTITY(nickname):\e[0m"
  echo "_|-_|-_|-_|-_|-_|-_|"
  read MONIKER
  echo "_|-_|-_|-_|-_|-_|-_|"
  echo "export MONIKER="${MONIKER}"" >> $HOME/.bash_profile
  source $HOME/.bash_profile
fi

#----------------------------------------------------

PS3='Select an action: '
options=("Create a new wallet" "Recover an old wallet" "Exit")
select opt in "${options[@]}"
do
  case $opt in
    "Create a new wallet")
      command="namada wallet address gen --alias wallet && namada wallet key list && namada wallet address list && echo -e '      \e[1m\e[31m!!!!!!!!!SAVE!!!!!!!!!!!!!!!!SAVE YOUR MNEMONIC PHRASE!!!!!!!!!SAVE!!!!!!!!!!!!!!!!\e[0m'"
      break
      ;;
    "Recover an old wallet")
      command="namada wallet key derive --alias wallet --hd-path default && namada wallet key list && namada wallet address list"
      break
      ;;
    "Exit")
      exit
      ;;
    *) echo "Invalid option. Please try again.";;
  esac
done

#----------------------------------------------------

echo "export NAMADA_CHAIN_ID=shielded-expedition.b40d8e9055" >> $HOME/.bash_profile
echo "export NAMADA_PORT=41" >> $HOME/.bash_profile
source $HOME/.bash_profile

#----------------------------------------------------

apt update && apt upgrade -y

# Update or install rust
if command -v rustup &> /dev/null; then
    rustup update
else
    curl https://sh.rustup.rs -sSf | sh
    source $HOME/.cargo/env
fi

#----------------------------------------------------

if command -v cometbft &> /dev/null; then
    cometbft version
else
    cd $HOME
    git clone https://github.com/cometbft/cometbft.git
    cd cometbft
    git checkout v0.37.2
    make install
    cp $(which cometbft) /usr/local/bin/ && cd $HOME
    cometbft version
fi

#----------------------------------------------------

# Update the repositories
sudo apt-get install -y make git-core libssl-dev pkg-config libclang-12-dev build-essential protobuf-compiler

if [ ! -d ~/protobuf-3.12.0 ]; then
rm /usr/bin/protoc
cd $HOME && wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protobuf-all-3.12.0.tar.gz
tar -xzvf protobuf-all-3.12.0.tar.gz
rm protobuf-all-3.12.0.tar.gz
cd protobuf-3.12.0
./configure
make
sudo make install
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
fi

#----------------------------------------------------

cd $HOME && git clone https://github.com/anoma/namada.git
cd namada && git checkout v0.31.0
make install
cp ~/namada/target/release/namada* /usr/local/bin/

#----------------------------------------------------

namada client utils join-network --chain-id $NAMADA_CHAIN_ID

sed -i.bak -e "s%:26658%:${NAMADA_PORT}658%g;
s%:26657%:${NAMADA_PORT}657%g;
s%:26656%:${NAMADA_PORT}656%g;
s%:26545%:${NAMADA_PORT}545%g;
s%:8545%:${NAMADA_PORT}545%g;
s%:26660%:${NAMADA_PORT}660%g" ~/.local/share/namada/$NAMADA_CHAIN_ID/config.toml

# Open ports
ufw allow ${NAMADA_PORT}658
ufw allow ${NAMADA_PORT}657
ufw allow ${NAMADA_PORT}545
ufw allow ${NAMADA_PORT}660

#----------------------------------------------------

sudo tee /etc/systemd/system/namadad.service > /dev/null <<EOF
[Unit]
Description=namada
After=network-online.target
[Service]
User=$USER
WorkingDirectory=$HOME/.local/share/namada
Environment=CMT_LOG_LEVEL=p2p:none,pex:error
Environment=NAMADA_CMT_STDOUT=true
ExecStart=/usr/local/bin/namada node ledger run 
StandardOutput=syslog
StandardError=syslog
Restart=always
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable namadad
sudo systemctl restart namadad

eval "$command"

echo '=============== INSLALL FINISHED ==================='
echo -e "To check logs:    \e[1m\e[33mjournalctl -u namadad -f -o cat\e[0m"

break
;;

#=======================================================

"Update")

sudo systemctl stop namadad

echo "export NAMADA_CHAIN_ID=shielded-expedition.b40d8e9055" >> $HOME/.bash_profile
source $HOME/.bash_profile

#----------------------------------------------------

# Update or install rust
if command -v rustup &> /dev/null; then
    rustup update
else
    curl https://sh.rustup.rs -sSf | sh
    source $HOME/.cargo/env
fi
rustc --version

#----------------------------------------------------

if [ ! -d ~/protobuf-3.12.0 ]; then
# Update the repositories
sudo apt-get install -y make git-core libssl-dev pkg-config libclang-12-dev build-essential protobuf-compiler
rm /usr/bin/protoc
cd $HOME && wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protobuf-all-3.12.0.tar.gz
tar -xzvf protobuf-all-3.12.0.tar.gz
rm protobuf-all-3.12.0.tar.gz
cd protobuf-3.12.0
./configure
make
sudo make install
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
fi

#----------------------------------------------------

cd $HOME
if [ ! -d ~/namada ]; then
git clone https://github.com/anoma/namada.git
fi
cd namada
git pull
git checkout v0.31.0
make install
cp ~/namada/target/release/namada* /usr/local/bin/
namada client utils join-network --chain-id $NAMADA_CHAIN_ID

#----------------------------------------------------

sed -i.bak -e "s%:26658%:${NAMADA_PORT}658%g;
s%:26657%:${NAMADA_PORT}657%g;
s%:26656%:${NAMADA_PORT}656%g;
s%:26545%:${NAMADA_PORT}545%g;
s%:8545%:${NAMADA_PORT}545%g;
s%:26660%:${NAMADA_PORT}660%g" ~/.local/share/namada/$NAMADA_CHAIN_ID/config.toml

sudo systemctl restart namadad

#----------------------------------------------------

# namada wallet key derive --alias wallet --hd-path default && namada wallet key list && namada wallet address list

#----------------------------------------------------

break
;;

#=======================================================

"Delete")

sudo systemctl stop namadad
sudo systemctl disable namadad
rm -rf namada ~/.local/share/namada/
rm /usr/local/bin/namada*
rm /etc/systemd/system/namadad.service
sudo systemctl daemon-reload

break
;;

#=======================================================

"Exit")
exit
;;
*) echo "Invalid option. Please try again.";;
esac

done
