#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

PS3='Select an action: '
options=(
"Install Node"
"Update Node"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in
#================================================================

"Install Node")

sudo apt remove --purge protobuf-compiler -y

PROTOC_VERSION=23.4
cd /usr/local

sudo curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip

sudo unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip

sudo rm protoc-${PROTOC_VERSION}-linux-x86_64.zip

sudo ln -sf /usr/local/bin/protoc /usr/bin/protoc

cd

screen -S nexus

curl -sSf https://cli.nexus.xyz/ | sh

break
;;

#================================================================

"Update Node")
#
#
break
;;

#================================================================

"Delete Node")
#
#
break
;;

#================================================================

"Exit")
exit
esac
done
