#!/bin/bash
#!/usr/bin/expect -f

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

if [ -z "$MONIKER" ]; then
  echo "*********************"
  echo -e "\e[1m\e[34m		Lets's begin\e[0m"
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your MONIKER:\e[0m"
  echo "*********************"
  read MONIKER
  echo 'export MONIKER='$MONIKER >> $HOME/.bash_profile
  source ~/.bash_profile
fi

if [ -z "$SUBSPACE_ADDRESS" ]; then
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your SUBSPACE_ADDRESS:\e[0m"
  echo "*********************"
  read SUBSPACE_ADDRESS
  echo 'export SUBSPACE_ADDRESS='$SUBSPACE_ADDRESS >> $HOME/.bash_profile
  source ~/.bash_profile
fi

# Update the repositories
apt update && apt upgrade -y

# Install developer packages (One command)
sudo apt-get install wget jq ocl-icd-opencl-dev \
libopencl-clang-dev libgomp1 ocl-icd-libopencl1 -y

cpu_version=$(echo 'BEGIN {
    while (!/flags/) if (getline < "/proc/cpuinfo" != 1) exit 1
    if (/lm/&&/cmov/&&/cx8/&&/fpu/&&/fxsr/&&/mmx/&&/syscall/&&/sse2/) level = 1
    if (level == 1 && /cx16/&&/lahf/&&/popcnt/&&/sse4_1/&&/sse4_2/&&/ssse3/) level = 2
    if (level == 2 && /avx/&&/avx2/&&/bmi1/&&/bmi2/&&/f16c/&&/fma/&&/abm/&&/movbe/&&/xsave/) level = 3
    if (level == 3 && /avx512f/&&/avx512bw/&&/avx512cd/&&/avx512dq/&&/avx512vl/) level = 4
    if (level > 0) { print "CPU supports x86-64-v" level; exit level + 1 }
    exit 1
}' | awk -f -)

if [ "$cpu_version" = "CPU supports x86-64-v3" ]; then
  VER=$(wget -qO- https://api.github.com/repos/subspace/subspace-cli/releases | jq '.[] | select(.prerelease==false) | select(.draft==false) | .html_url' | grep -Eo "v[0-9]+\.[0-9]+\.[0-9]+.*$" | sed 's/.$//' | head -n 1) && \
  cd /usr/local/bin/ && wget https://github.com/subspace/subspace-cli/releases/download/${VER}/subspace-cli-ubuntu-x86_64-skylake-${VER} -qO subspace
else
  VER=$(wget -qO- https://api.github.com/repos/subspace/subspace-cli/releases | jq '.[] | select(.prerelease==false) | select(.draft==false) | .html_url' | grep -Eo "v[0-9]+\.[0-9]+\.[0-9]+.*$" | sed 's/.$//' | head -n 1) && \
  cd /usr/local/bin/ && wget https://github.com/subspace/subspace-cli/releases/download/${VER}/subspace-cli-ubuntu-x86_64-v2-${VER} -qO subspace
fi

# Next step..
sudo chmod +x subspace && cd
echo -e "\n\nrelease >> ${VER}.\n\n"

# Automation of the subspace init command
spawn subspace init

expect "Do you have an existing farmer/reward address? [y/n]:"
send "y\r"

expect "Enter your farmer/reward address:"
send "$env(SUBSPACE_ADDRESS)\r"

expect "Enter your node name to be identified on the network (defaults to 'root', press enter to use the default):"
send "$env(MONIKER)\r"

expect "Specify a path for storing plot files (press enter to use the default: '/root/.local/share/subspace-cli/plots'):"
send "\r"

expect "Specify a path for storing node files (press enter to use the default: '/root/.local/share/subspace-cli/node'):"
send "\r"

expect "Specify a plot size (defaults to '2.0 GB', press enter to use the default):"
send "100 GB\r"

expect "Defaults to 'Gemini3e', press enter to use the default:"
send "\r"

# Fix journal (One command)
sudo tee <<EOF >/dev/null /etc/systemd/journald.conf
Storage=persistent
EOF

# Restart journal
sudo systemctl restart systemd-journald

# Create service file (One command)
sudo tee <<EOF >/dev/null /etc/systemd/system/subspaced.service
[Unit]
Description=Subspace Node
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which subspace) farm -v
StandardOutput=syslog
StandardError=syslog
Restart=always
RestartSec=3
LimitNOFILE=1024000
[Install]
WantedBy=multi-user.target
EOF

# Start the node
sudo systemctl daemon-reload && \
sudo systemctl enable subspaced && \
sudo systemctl restart subspaced

echo '=============== SETUP FINISHED ==================='
echo -e 'Congratulations:        \e[1m\e[32mSUCCESSFUL NODE INSTALLATION\e[0m'
echo -e 'To check logs:        \e[1m\e[33msudo journalctl -fu subspaced --no-hostname -o cat\e[0m'
