#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

# Menu
PS3='Select an action: '
options=(
"Install Node"
"Update"
"Install Operator"
"Delete"
"Exit")

select opt in "${options[@]}"
do
case $opt in
"Install Node")

#===============================================================

if [ -z "$MONIKER" ]; then
  echo "*********************"
  echo -e "\e[1m\e[34m		Lets's begin\e[0m"
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your MONIKER:\e[0m"
  echo "*********************"
  read MONIKER
  echo 'export MONIKER='$MONIKER >> $HOME/.bash_profile
  source ~/.bash_profile
fi

if [ -z "$SUBSPACE_ADDRESS" ]; then
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your SUBSPACE_ADDRESS:\e[0m"
  echo "*********************"
  read SUBSPACE_ADDRESS
  echo 'export SUBSPACE_ADDRESS='$SUBSPACE_ADDRESS >> $HOME/.bash_profile
  source ~/.bash_profile
fi

echo "*********************"
echo -e "\e[1m\e[32m	Enter your PLOT_SIZE in GB:\e[0m"
echo "*********************"
read PLOT_SIZE

# Update the repositories
# apt update && apt upgrade -y

mkdir $HOME/subspace; \
cd $HOME/subspace && \
wget https://github.com/subspace/subspace/releases/download/gemini-3g-2023-dec-20/subspace-farmer-ubuntu-x86_64-skylake-gemini-3g-2023-dec-20 -O farmer && \
wget https://github.com/subspace/subspace/releases/download/gemini-3g-2023-dec-20/subspace-node-ubuntu-x86_64-skylake-gemini-3g-2023-dec-20 -O subspace && \
sudo chmod +x * && \
sudo mv * /usr/local/bin/ && \
cd $HOME && \
rm -Rvf $HOME/subspace && \
mkdir $HOME/.local/share/subspace-farmer

sudo tee <<EOF >/dev/null /etc/systemd/system/subspaced.service
[Unit]
Description=Subspace Node
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which subspace) \\
--chain="gemini-3g" \\
--blocks-pruning="256" \\
--state-pruning="archive-canonical" \\
--no-private-ipv4 \\
--validator \\
--name="$MONIKER"
Restart=on-failure
RestartSec=10
LimitNOFILE=1024000
[Install]
WantedBy=multi-user.target
EOF

sudo tee <<EOF >/dev/null /etc/systemd/system/subspacefarm.service
[Unit]
Description=Subspace Farmer
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which farmer) farm --reward-address=$SUBSPACE_ADDRESS path=$HOME/.local/share/subspace-farmer,size=${PLOT_SIZE}G 
Restart=always
RestartSec=10
LimitNOFILE=1024000
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl restart systemd-journald
sudo systemctl daemon-reload
sudo systemctl enable subspaced subspacefarm
sudo systemctl restart subspacefarm subspaced

echo '=============== INSLALL FINISHED ==================='
echo -e "To check node logs:      \e[1m\e[33msudo journalctl -fu subspaced --no-hostname -o cat\e[0m"
echo -e "To check farmer logs:    \e[1m\e[33msudo journalctl -fu subspacefarm --no-hostname -o cat\e[0m"

break
;;

#===========================================================================

"Update")

echo "*********************"
echo -e "\e[1m\e[32m	Enter your PLOT_SIZE in GB:\e[0m"
echo "*********************"
read PLOT_SIZE

if [ -z "$SUBSPACE_ADDRESS" ]; then
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your SUBSPACE_ADDRESS:\e[0m"
  echo "*********************"
  read SUBSPACE_ADDRESS
  echo 'export SUBSPACE_ADDRESS='$SUBSPACE_ADDRESS >> $HOME/.bash_profile
  source ~/.bash_profile
fi

sudo systemctl stop subspaced subspacefarm
mkdir $HOME/subspace
cd $HOME/subspace
wget https://github.com/subspace/subspace/releases/download/gemini-3g-2023-dec-20/subspace-farmer-ubuntu-x86_64-skylake-gemini-3g-2023-dec-20 -O farmer
wget https://github.com/subspace/subspace/releases/download/gemini-3g-2023-dec-20/subspace-node-ubuntu-x86_64-skylake-gemini-3g-2023-dec-20 -O subspace
sudo chmod +x *
rm /usr/local/bin/farmer
rm /usr/local/bin/subspace
sudo mv * /usr/local/bin/
cd $HOME && \
rm -Rvf $HOME/subspace

sudo tee <<EOF >/dev/null /etc/systemd/system/subspacefarm.service
[Unit]
Description=Subspace Farmer
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which farmer) farm \\
--reward-address=$SUBSPACE_ADDRESS path=$HOME/.local/share/subspace-farmer,size=${PLOT_SIZE}G
Restart=always
RestartSec=10
LimitNOFILE=1024000
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl restart subspacefarm subspaced

echo '=============== UPDATE FINISHED ==================='
echo -e "To check node logs:      \e[1m\e[33msudo journalctl -fu subspaced --no-hostname -o cat\e[0m"
echo -e "To check farmer logs:    \e[1m\e[33msudo journalctl -fn1000 -u subspacefarm --no-hostname -o cat\e[0m"

break
;;

#===========================================================================

"Install Operator")

if [ -z "$MONIKER" ]; then
  echo "*********************"
  echo -e "\e[1m\e[34m		Lets's begin\e[0m"
  echo "*********************"
  echo -e "\e[1m\e[32m	Enter your MONIKER:\e[0m"
  echo "*********************"
  read MONIKER
  echo 'export MONIKER='$MONIKER >> $HOME/.bash_profile
  source ~/.bash_profile
fi

sudo systemctl stop subspaced subspacefarm

rm -rf $HOME/.local/share/subspace-node/chains/subspace_gemini_3g/paritydb/full

sudo tee <<EOF >/dev/null /etc/systemd/system/subspaced.service
[Unit]
Description=Subspace Node
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which subspace) \\
--chain="gemini-3g" \\
--blocks-pruning="256" \\
--state-pruning="archive-canonical" \\
--no-private-ipv4 \\
--validator \\
--name="$MONIKER" \\
-- \\
--domain-id 1 \\
--keystore-path $HOME/.local/share/subspace-node/chains/subspace_gemini_3g/keystore/ \\
--listen-addr /ip4/0.0.0.0/tcp/40333
Restart=on-failure
RestartSec=10
LimitNOFILE=1024000
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl restart subspacefarm subspaced

echo '=============== OPERATOR INSTALLED ==================='
echo -e "To check node logs:      \e[1m\e[33msudo journalctl -fu subspaced --no-hostname -o cat\e[0m"
echo -e "To check farmer logs:    \e[1m\e[33msudo journalctl -fn1000 -u subspacefarm --no-hostname -o cat\e[0m"

break
;;

#===========================================================================

"Delete")

sudo systemctl stop subspaced subspacefarm && \
sudo systemctl disable subspaced subspacefarm 

rm -Rvf $HOME/.local/share/subspace* \
/usr/local/bin/subspace \
/usr/local/bin/farmer

sudo rm -v /etc/systemd/system/subspaced.service && \
sudo rm -v /etc/systemd/system/subspacefarm.service && \
sudo systemctl daemon-reload

break
;;

#===========================================================================

"Exit")
exit
;;
*) echo "Invalid option. Please try again.";;
esac

done
