#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/logo.sh | bash

#=======================================================

# Menu
PS3='Select an action: '
options=(
"Install Node"
"Update"
"Delete"
"Exit")

#=======================================================

select opt in "${options[@]}"
do
case $opt in
"Install Node")

#----------------------------------------------------

if [ -z "$RPC_HOLESKY" ]; then
  if [ -z "$RPC_SEPOLIA" ]; then
    echo -e "      \e[1m\e[35m Input RPC_HOLESKY:\e[0m"
    echo "_|-_|-_|-_|-_|-_|-_|"
    read RPC_HOLESKY
    echo "_|-_|-_|-_|-_|-_|-_|"
  else
    RPC_HOLESKY="${RPC_SEPOLIA/sepolia/holesky}"
  fi
  echo 'export RPC_HOLESKY='$RPC_HOLESKY >> $HOME/.bash_profile
fi

if [ -z "$WS_HOLESKY" ]; then
  if [ -z "$RPC_HOLESKY" ]; then
    echo -e "      \e[1m\e[35m Input WS_HOLESKY:\e[0m"
    echo "_|-_|-_|-_|-_|-_|-_|"
    read WS_HOLESKY
    echo "_|-_|-_|-_|-_|-_|-_|"
  else
    WS_HOLESKY="${RPC_HOLESKY/https/wss}"
  fi
  echo 'export WS_HOLESKY='$WS_HOLESKY >> $HOME/.bash_profile
fi

#if [ -z "$EVM_ADDRESS" ]; then
#  echo -e "      \e[1m\e[35m Input EVM_ADDRESS:\e[0m"
#  echo "_|-_|-_|-_|-_|-_|-_|"
#  read EVM_ADDRESS
#  echo "_|-_|-_|-_|-_|-_|-_|"
#  echo "export EVM_ADDRESS="${EVM_ADDRESS}"" >> $HOME/.bash_profile
#fi

source $HOME/.bash_profile

#echo "*********************"
#read -p "Enter your private key:" PROVER_PRIVATE_KEY

# Update the repositories
apt update && apt upgrade -y

#Instal or Update Git
sudo apt-get install git-all -y

# Install Docker
if ! [ -x "$(command -v docker)" ]; then
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
sudo usermod -aG docker $USER
docker --version
else
echo $(docker --version)
fi

#Clone simple-taiko-node
git clone https://github.com/taikoxyz/simple-taiko-node.git taiko
cd taiko

#Copy the sample .env files
cp .env.sample .env

sed -i "s|^L1_ENDPOINT_HTTP=.*|L1_ENDPOINT_HTTP=$RPC_SEPOLIA|" .env
sed -i "s|^L1_ENDPOINT_WS=.*|L1_ENDPOINT_WS=$WS_SEPOLIA|" .env
sed -i 's/^PORT_GRAFANA=.*/PORT_GRAFANA=4301/' .env
#sed -i "s|^L1_PROVER_PRIVATE_KEY=.*|L1_PROVER_PRIVATE_KEY=$PROVER_PRIVATE_KEY|" .env
#sed -i 's/^ENABLE_PROVER=.*/ENABLE_PROVER=true/' .env
#sed -i "s|^L1_PROPOSER_PRIVATE_KEY=.*|L1_PROPOSER_PRIVATE_KEY=$PROVER_PRIVATE_KEY|" .env
#sed -i "s|^L2_SUGGESTED_FEE_RECIPIENT=.*|L2_SUGGESTED_FEE_RECIPIENT=$EVM_ADDRESS|" .env

docker compose up -d

break
;;

#=======================================================

"Exit")
exit
;;
*) echo "Invalid option. Please try again.";;
esac

done
