#!/bin/bash

echo "1 - $(grep -E '^identity_key = "(.*)"' validator.toml | awk -F '"' '{print $2}')
echo "2 - \$(grep -E '^identity_key = "(.*)"' validator.toml | awk -F '"' '{print \$2}')

#pcli query validator list -i | grep $(grep -E '^identity_key = "(.*)"' validator.toml | awk -F '"' '{print $2}')
