#!/bin/bash
# source <(curl -s https://raw.githubusercontent.com/NodersUA/Scripts/main/temp2)

mv /etc/systemd/system/df_titan-chain.service /etc/systemd/system/df_titan.service
sudo sed -i 's|^ExecStart=.*|ExecStart=/root/df_titan/db.sh|' /etc/systemd/system/df_titan.service
systemctl daemon-reload
systemctl restart df_titan
