#!/bin/bash

PUB_KEY_VALUE=$(jq -r '.pub_key.value' ~/.penumbra/testnet_data/node0/cometbft/config/priv_validator_key.json)

sequence_number=$(awk -F' = ' '/^sequence_number/ {print $2}' ~/penumbra/validator.toml)
((sequence_number++))
sed -i "s/^sequence_number *=.*/sequence_number = $sequence_number/" ~/penumbra/validator.toml

sed -i "s|^value *=.*|value = \"$PUB_KEY_VALUE\"|" ~/penumbra/validator.toml

pcli validator definition upload --file ~/penumbra/validator.toml
pcli query validator list -i | grep $PENUMBRA_VALIDATOR

pcli view balance
