echo "*****************************"
echo -e "\e[1m\e[32m Chain id:           $NODE_CHAIN_ID \e[0m"
echo -e "\e[1m\e[32m Chain demon:        $NODE_CHAIN_DENOM \e[0m"
echo -e "\e[1m\e[32m Node port:        $NODE_PORT \e[0m"
echo -e "\e[1m\e[32m Binary version tag: $BINARY_VERSION_TAG \e[0m"
echo "*****************************"
